### PR TITLE
upgrade jenkins slave to 1.1.0

### PR DESCRIPTION
**Pull request by pydevops**

### CODE REVIEW

**Comment by pydevops** [comment]
test this please

**Comment by pydevops** [comment]
test this please

**Comment by pydevops** [comment]
test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by pydevops** [comment]
test this please

**Comment by chrislovecnm** [comment]
@pydevops we may need to increase the TF timeout

```console
Wait for the BACKEND k8s-ig--e8eb079bdb87e679 being deleted.
Wait for the BACKEND k8s-ig--e8eb079bdb87e679 being deleted.
Wait for the BACKEND k8s-ig--e8eb079bdb87e679 being deleted.
Wait for the BACKEND k8s-ig--e8eb079bdb87e679 being deleted.
Wait for the BACKEND k8s-ig--e8eb079bdb87e679 being deleted.
Retry limit exceeded; exiting...
Makefile:98: recipe for target 'tf-destroy' failed
```

**Pull request merged**
