### PR TITLE
update gke version to use latest tf validMasterVersion

### PR DESCRIPTION
**Pull request by edwardmedia**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Can we figure out why CI failed?

**Comment by edwardmedia** [comment]
This appears to be an existing issue. here is the error which is the same appeared in the "trouble shooting" section in the readme file
* google_compute_network.gke-network: The network resource 'projects/pso-helmsman-cicd-infra/global/networks/kube-net' is already being used by 'projects/pso-helmsman-cicd-infra/global/firewalls/k8s-e8eb079bdb87e679-node-hc'

**Comment by edwardmedia** [comment]
Let's figure out a solution to resolve this

**Comment by chrislovecnm** [comment]
Please rebase and pull in the new commit.

**Pull request closed without merging**
