### PR TITLE
Adding README-QWIKLABS.md and fixed broken links

### PR DESCRIPTION
**Pull request by mvoora**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/ok-to-test
ok test test

**Comment by chrislovecnm** [comment]
/hold

We need to you join the org

**Comment by mvoora** [comment]
I am  part of the GoogleCloudPlatform org.

**Comment by homernajafi** [comment]
Test this please

**Comment by mvoora** [comment]
Test this please

**Pull request merged**
